### ISSUE TITLE
Missing libowgameevents\samples

### ISSUE THREAD

**Issue by Titanic4** [overwolf/game-events-sdk#3]
According to the README.md file, CPP and CSharp sample applications and code should be available in libowgameevents\samples subfolder, however I can't seem to find it.

**Comment by tomwolfgang** [comment]
This is where the CPP sample is: https://github.com/overwolf/game-events-sdk/tree/master/Samples/CPP
For C# - just use: https://github.com/overwolf/game-events-sdk/blob/master/libowgameevents/csharp/OwGameEventsDllWrapper.cs


btw - this sdk is mainly for game developers - for Oerwolf app developers please look at: https://overwolf.github.io/docs/api/overwolf-games-events
